import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MainLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <head>
            <title>{metadata.title ?? "Default Title"}</title>
            <meta name="description" content={metadata.description ?? "Default description"} />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        <main className="container mx-auto p-4">{children}</main>
        <Footer />
        </body>
        </html>
    );
}
